---
title: "RMarkdown-Leaflet Assigment"
author: "Francisco Javier Rincón"
date: "October 14, 2017"
output: html_document
---

Create a web page using R Markdown that features a map created with Leaflet.

Top Ten Places to visit in Brazil

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
```

```{r top_ten_places_brazil}
top_ten_places_brazil <- data.frame(name = c("Noronha-PE","Búzios-RJ", "Jericoacoara-CE", "Porto de Galinhas-PE", "Angra dos Reis-RJ",
                                 "Ilhabela-SP", "Bonito-RS", "Maragogi-AL", "Iguzú-PA", "Paraty-RJ"),
                        pop = c(619493, 66169, 62334, 61045, 55232,
                                39890, 38880, 30587, 30484, 25346),
                        lat = c(-3.8447, -22.7564, -2.7956, -8.4844, -23.0057, -23.8158, -21.1286, -9.0103, -25.6667, -23.22),
                        lng = c(-32.4268, -41.889, -40.5142, -34.9996, -44.3158, -45.3664, -56.4928, -35.2208,  -54.45, -44.7204), color = sample(colors(), 100))


  top_ten_places_brazil %>%
  leaflet() %>%
  addTiles() %>%
  addCircles(weight = 10, radius = sqrt(top_ten_places_brazil$pop) * 30, color= ~color, fill = FALSE, label = top_ten_places_brazil$name, 
             labelOptions = labelOptions(noHide = T, direction = "right",
      style = list(
        "color" = "green",
        "font-family" = "serif",
        "font-style" = "italic",
        "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
        "font-size" = "10px",
        "border-color" = "rgba(0,0,0,0.2)"
      )))
    
```

